/* ============================================================
   MyCron — data.jsx : mock cronlets, runs, evidence manifests
   ============================================================ */

// weekly health arrays read Mon→Sun. values: verified|failed|stale|unverified|null
const CRONLETS = [
  {
    id: "cl_portfolio",
    name: "Daily Portfolio Brief",
    icon: "trend",
    intent: "Summarize overnight market moves and reconcile portfolio drift before the open.",
    agent: "FinAgent", runtime: "Hermes Cloud",
    scheduleHuman: "Every weekday · 09:00",
    cron: "0 9 * * 1-5", tz: "Asia/Seoul",
    nextRun: "Tomorrow · 09:00 KST",
    lastRun: "Today · 09:01 KST",
    lastDuration: "4.2s",
    state: "verified",
    health: ["verified","verified","verified","verified","verified","stale","verified"],
    verifiedRate: 0.92,
    runId: "run_8f2a91c",
    summary: "Indices closed mixed; portfolio drift +0.4% vs target. 3 sources reconciled, brief delivered to #mycron-daily.",
    donePolicy: [
      { id:"ran",   label:"Process completed",      detail:"Agent exited 0 in 4.2s",          state:"verified" },
      { id:"src",   label:"Required sources collected", detail:"5 of 5 market sources reached", state:"verified" },
      { id:"out",   label:"Output generated",        detail:"summary.pdf created (182 KB)",      state:"verified" },
      { id:"ev",    label:"Evidence captured",       detail:"3 links + file + delivery receipt", state:"verified" },
      { id:"goal",  label:"User goal satisfied",     detail:"Awaiting your confirmation",        state:"unverified" },
    ],
    evidence: [
      { type:"file",  icon:"fileText", label:"summary.pdf",        meta:"182 KB · generated 09:01:04", ref:"/runs/8f2a91c/summary.pdf" },
      { type:"links", icon:"link",     label:"3 source links",     meta:"reuters, bloomberg, krx — 200 OK", ref:"3 verified" },
      { type:"deliver",icon:"send",    label:"Slack delivery",     meta:"#mycron-daily · ts 1718··· ", ref:"receipt ✓" },
      { type:"log",   icon:"terminal", label:"Run log",            meta:"42 lines · 0 warnings",       ref:"tail" },
    ],
    readback: "mycron verify run_8f2a91c --evidence",
    cost: "$0.04",
  },
  {
    id: "cl_oss",
    name: "OSS Trend Watch",
    icon: "git",
    intent: "Scan tracked repositories and release feeds, surface notable movement for the day.",
    agent: "TrendAgent", runtime: "Hermes Cloud",
    scheduleHuman: "Daily · 14:00",
    cron: "0 14 * * *", tz: "Asia/Seoul",
    nextRun: "Tomorrow · 14:00 KST",
    lastRun: "Today · 14:00 KST",
    lastDuration: "11.8s",
    state: "unverified",
    health: ["verified","verified","unverified","verified","verified","unverified","verified"],
    verifiedRate: 0.74,
    runId: "run_b71d04e",
    summary: "Ran and produced output, but 1 of 15 sources (GitHub trending) returned a partial response. Evidence incomplete — completion not yet provable.",
    donePolicy: [
      { id:"ran",   label:"Process completed",       detail:"Agent exited 0 in 11.8s",        state:"verified" },
      { id:"src",   label:"Required sources collected", detail:"14 of 15 — 1 partial response",  state:"unverified" },
      { id:"out",   label:"Output generated",         detail:"digest.md created (24 KB)",        state:"verified" },
      { id:"ev",    label:"Evidence captured",        detail:"Source manifest incomplete",       state:"unverified" },
      { id:"goal",  label:"User goal satisfied",      detail:"Blocked on evidence",              state:"unverified" },
    ],
    evidence: [
      { type:"file",  icon:"fileText", label:"digest.md",        meta:"24 KB · generated 14:00:11", ref:"/runs/b71d04e/digest.md" },
      { type:"links", icon:"link",     label:"14 of 15 sources", meta:"github-trending → 206 partial", ref:"1 unverified", warn:true },
      { type:"log",   icon:"terminal", label:"Run log",          meta:"118 lines · 1 warning",      ref:"tail" },
    ],
    readback: "mycron verify run_b71d04e --evidence",
    cost: "$0.07",
  },
  {
    id: "cl_planning",
    name: "Morning Planning Reminder",
    icon: "sparkle",
    intent: "Assemble today's priorities from Obsidian + calendar and push a planning nudge.",
    agent: "PlanAgent", runtime: "Local runner",
    scheduleHuman: "Daily · 08:00",
    cron: "0 8 * * *", tz: "Asia/Seoul",
    nextRun: "Tomorrow · 08:00 KST",
    lastRun: "Today · 08:00 KST",
    lastDuration: "2.1s",
    state: "verified",
    health: ["verified","verified","verified","verified","verified","verified","verified"],
    verifiedRate: 0.99,
    runId: "run_3c5e120",
    summary: "Priorities assembled from 4 notes and today's calendar. Reminder delivered to Telegram, read receipt confirmed.",
    donePolicy: [
      { id:"ran",  label:"Process completed",        detail:"Agent exited 0 in 2.1s",        state:"verified" },
      { id:"src",  label:"Required sources collected", detail:"Obsidian + calendar reached",   state:"verified" },
      { id:"out",  label:"Output generated",          detail:"plan.md created",                state:"verified" },
      { id:"ev",   label:"Evidence captured",         detail:"Delivery + read receipt",         state:"verified" },
      { id:"goal", label:"User goal satisfied",       detail:"Confirmed via read receipt",      state:"verified" },
    ],
    evidence: [
      { type:"file",  icon:"fileText", label:"plan.md",        meta:"3 KB · generated 08:00:02", ref:"/runs/3c5e120/plan.md" },
      { type:"deliver",icon:"send",    label:"Telegram push",  meta:"read receipt confirmed 08:04", ref:"receipt ✓" },
      { type:"log",   icon:"terminal", label:"Run log",        meta:"18 lines · 0 warnings",     ref:"tail" },
    ],
    readback: "mycron verify run_3c5e120 --evidence",
    cost: "$0.01",
  },
  {
    id: "cl_backup",
    name: "Backup Health Check",
    icon: "shield",
    intent: "Probe storage backends and verify last snapshot is recent and restorable.",
    agent: "SafeAgent", runtime: "K8s CronJob",
    scheduleHuman: "Daily · 10:30",
    cron: "30 10 * * *", tz: "Asia/Seoul",
    nextRun: "Retry queued · 10:45 KST",
    lastRun: "Today · 10:30 KST",
    lastDuration: "—",
    state: "failed",
    health: ["verified","verified","failed","verified","stale","verified","failed"],
    verifiedRate: 0.61,
    runId: "run_e09a7f3",
    summary: "Storage health endpoint did not respond within 30s. No snapshot verified today. Last good check was 2 days ago.",
    errorType: "UpstreamTimeout",
    lastSuccess: "2 days ago · Jun 6, 10:30",
    donePolicy: [
      { id:"ran",  label:"Process completed",        detail:"Timed out after 30s — exit 124",  state:"failed" },
      { id:"src",  label:"Required sources collected", detail:"storage-api unreachable",        state:"failed" },
      { id:"out",  label:"Output generated",          detail:"No artifact produced",            state:"failed" },
      { id:"ev",   label:"Evidence captured",         detail:"Failure trace captured",          state:"verified" },
      { id:"goal", label:"User goal satisfied",       detail:"Not satisfied — escalated",       state:"failed" },
    ],
    evidence: [
      { type:"log",   icon:"terminal", label:"Failure trace",  meta:"exit 124 · UpstreamTimeout", ref:"tail", warn:true },
      { type:"links", icon:"link",     label:"storage-api",    meta:"GET /healthz → no response", ref:"0 of 1", warn:true },
    ],
    readback: "mycron logs run_e09a7f3 --tail",
    cost: "$0.00",
  },
  {
    id: "cl_repo",
    name: "Weekly Repo Digest",
    icon: "git",
    intent: "Compile merged PRs, new issues and contributor stats into a Monday digest.",
    agent: "CodeAgent", runtime: "GitHub Actions",
    scheduleHuman: "Mondays · 07:00",
    cron: "0 7 * * 1", tz: "Asia/Seoul",
    nextRun: "Overdue · expected 9 days ago",
    lastRun: "9 days ago · May 30",
    lastDuration: "—",
    state: "stale",
    health: ["verified",null,null,null,null,null,null],
    verifiedRate: 0.55,
    runId: "run_a1b88c0",
    summary: "Has not executed for 9 days — the GitHub Actions trigger appears to have drifted. No failure was reported; the schedule simply stopped firing.",
    lastSuccess: "9 days ago · May 30, 07:00",
    donePolicy: [
      { id:"ran",  label:"Process completed",        detail:"No run recorded since May 30",    state:"stale" },
      { id:"src",  label:"Required sources collected", detail:"—",                              state:"stale" },
      { id:"out",  label:"Output generated",          detail:"—",                              state:"stale" },
      { id:"ev",   label:"Evidence captured",         detail:"—",                              state:"stale" },
      { id:"goal", label:"User goal satisfied",       detail:"Schedule drift — needs attention", state:"stale" },
    ],
    evidence: [
      { type:"log", icon:"history", label:"Last good run", meta:"May 30 · 07:00 · verified", ref:"run_77f0" },
    ],
    readback: "mycron schedule run_a1b88c0 --diagnose",
    cost: "—",
  },
  {
    id: "cl_inbox",
    name: "Inbox Triage",
    icon: "inbox",
    intent: "Classify new mail, draft replies for routine threads, flag anything needing a human.",
    agent: "MailAgent", runtime: "Local runner",
    scheduleHuman: "Hourly · business hours",
    cron: "0 9-18 * * 1-5", tz: "Asia/Seoul",
    nextRun: "In 38 min · 15:00 KST",
    lastRun: "Today · 14:00 KST",
    lastDuration: "6.4s",
    state: "verified",
    health: ["verified","verified","verified","stale","verified","verified","verified"],
    verifiedRate: 0.88,
    runId: "run_55c1aa2",
    summary: "Triaged 23 messages, drafted 4 replies, flagged 2 for review. All actions logged with reversible drafts.",
    donePolicy: [
      { id:"ran",  label:"Process completed",        detail:"Agent exited 0 in 6.4s",     state:"verified" },
      { id:"src",  label:"Required sources collected", detail:"Mailbox synced",            state:"verified" },
      { id:"out",  label:"Output generated",          detail:"4 drafts created",           state:"verified" },
      { id:"ev",   label:"Evidence captured",         detail:"Action log + draft refs",     state:"verified" },
      { id:"goal", label:"User goal satisfied",       detail:"2 items flagged for you",     state:"unverified" },
    ],
    evidence: [
      { type:"file",  icon:"fileText", label:"action_log.json", meta:"23 actions recorded",    ref:"/runs/55c1aa2/log.json" },
      { type:"links", icon:"link",     label:"4 draft replies",  meta:"reversible · not sent",  ref:"4 drafts" },
    ],
    readback: "mycron verify run_55c1aa2 --evidence",
    cost: "$0.03",
  },
];

// routine inbox — vague agent requests awaiting promotion to cronlets
const INBOX = [
  { id:"in1", text:"every morning check if my staging deploy is healthy and tell me", source:"Claude Code", time:"2h ago" },
  { id:"in2", text:"weekly, summarize what changed in the competitor pricing pages", source:"Telegram", time:"1d ago" },
  { id:"in3", text:"remind me to review the on-call rotation before each Monday", source:"Obsidian", time:"3d ago" },
];

// weekly review numbers (no vanity metrics — operational facts)
const WEEK = {
  range: "Jun 2 – Jun 8",
  verifiedRuns: 18, totalRuns: 24,
  prevVerified: 15,
  failed: 2, stale: 1, unverified: 3,
  cost: "$0.41",
  corrections: 2,
};

const STATE_ORDER = ["failed","stale","unverified","verified"];
function countByState() {
  const c = { verified:0, failed:0, stale:0, unverified:0 };
  CRONLETS.forEach(x => c[x.state]++);
  return c;
}

Object.assign(window, { CRONLETS, INBOX, WEEK, STATE_ORDER, countByState });
